### ISSUE TITLE
Reduce script unreachable?

### ISSUE THREAD

**Issue by drinks** [imotov/elasticsearch-facet-script#3]
I apologize for opening an issue when I'm really just looking for a clarification; but I'm unsure of how the various query phases are meant to be run. I've noticed that when running your example, the reduce script gets skipped because there is only one facet clause in the query, so the if clause at line 98 of ScriptFacetProcessor.java is executed. It doesn't feel to me like the desired behavior to have reduce run across all facet queries, and then only if there's more than one submitted. Am I completely missing how this is supposed to work?

FWIW, I've built the plugin to target 0.20.2 so it's feasible that something in the API has changed, though I don't believe that to be the case.

**Comment by imotov** [comment]
The reduce script doesn't run when you execute the charfreq.sh example because this example creates an index with a single shard. If you will change the number of shards to 2 or more, it will be no longer skipped. The purpose of the reduce script is to collect results from all shards and then reduce them into a single result. If there is only one shard, there is really nothing to reduce.

**Comment by drinks** [comment]
Thanks for this explanation, makes perfect sense. I'm left with one question, however: The reduce script in this case does generate a return value that you'd want regardless of the number of shards. On a single-shard index you get back a simple array of counts, whereas charfreq_reduce.mvel#L21 returns a hash of counts/total/freqs. Seems like you'd want that regardless of the number of shards, right?

Anywho, thanks much for clarifying, I can work w/ your answer.

**Comment by imotov** [comment]
Yes, you are absolutely right, I need to fix that.
